/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Skill, Project, Experience, Education } from './types';

export const personalInfo = {
  fullName: 'Keerthanavalli R',
  professionalTitle: 'Full-Stack Developer',
  email: 'rkvravindran4623@gmail.com',
  phone: '+91 96775 25528',
  location: 'Karaikudi, Sivagangai, Tamil Nadu',
  githubUrl: 'https://github.com/rkvkeerthana',
  linkedinUrl: 'https://linkedin.com/in/keerthanavallirkv',
  bio: 'Results-driven Full-Stack Developer with 3 years of experience in developing and maintaining scalable web applications, CRM systems, and inventory management platforms. Experienced in working on frontend and backend development, API integration, and database management. Strong understanding of React.js, PHP, Laravel, TypeScript, and MySQL, with hands-on experience in building responsive user interfaces and secure backend services.',
  aboutDetailed: 'I am a Software Engineer and Full-Stack Developer with 3 years of experience crafting high-performance, responsive web applications. My expertise spans React.js and TypeScript on the frontend, and PHP, Laravel, and Node.js on the backend. I have a proven track record of optimizing database queries, building secure RESTful APIs with granular access control, and leading small engineering teams to deliver milestones ahead of schedule. I focus on writing clean, maintainable code that solves real business problems.',
  typingTexts: [
    'Full-Stack Developer',
    'React.js & PHP Developer',
    'Laravel & Node.js Developer',
    'Clean Code Developer',
  ],
  quickStats: [
    { label: 'Years of Experience', value: '3' },
    { label: 'Core Tech Stack', value: 'React & PHP' },
    { label: 'Figma Integration', value: 'Pixel-Perfect' },
    { label: 'Coding Standard', value: 'Clean & DRY' },
  ],
  strengths: [
    { title: 'Responsive Interfaces', desc: 'Crafting pixel-perfect, cross-device compatible layouts using React.js and Tailwind CSS.' },
    { title: 'Secure API & Backend', desc: 'Implementing robust backend systems with PHP, Laravel, Node.js, and role-based access control.' },
    { title: 'Database Optimization', desc: 'Designing efficient database schemas and optimizing MySQL queries for minimal latency.' },
  ],
};

export const skillsData: Skill[] = [
  // Frontend Skills
  {
    name: 'React.js',
    category: 'Frontend',
    level: 95,
    iconName: 'React',
    description: 'Component architecture, state management, hooks, and responsive rendering optimization.',
  },
  {
    name: 'TypeScript',
    category: 'Frontend',
    level: 90,
    iconName: 'TypeScript',
    description: 'Robust type safety, modular structures, and cleaner compiler practices.',
  },
  {
    name: 'Tailwind CSS',
    category: 'Frontend',
    level: 95,
    iconName: 'Tailwind',
    description: 'Utility-first styling, fluid responsiveness, and high-performance design layouts.',
  },
  {
    name: 'JavaScript (ES6+)',
    category: 'Frontend',
    level: 95,
    iconName: 'JS',
    description: 'Asynchronous scripting, event loops, DOM control, and functional patterns.',
  },
  {
    name: 'Bootstrap',
    category: 'Frontend',
    level: 85,
    iconName: 'Bootstrap',
    description: 'Responsive grid designs and cross-browser visual compatibility layout setups.',
  },

  // Backend & DB
  {
    name: 'PHP & Laravel',
    category: 'Backend & DB',
    level: 92,
    iconName: 'PHP',
    description: 'Laravel frameworks, MVC design, custom routing, and database integrations.',
  },
  {
    name: 'Node.js',
    category: 'Backend & DB',
    level: 85,
    iconName: 'Node',
    description: 'Server APIs, JSON data exchanges, and middleware pipeline setups.',
  },
  {
    name: 'MySQL',
    category: 'Backend & DB',
    level: 90,
    iconName: 'SQL',
    description: 'Schema designs, table relations, indexes, and complex query optimizations.',
  },
  {
    name: 'RESTful APIs',
    category: 'Backend & DB',
    level: 92,
    iconName: 'API',
    description: 'Secure authentication integrations, route handlers, and data payloads.',
  },

  // Tools & Platforms
  {
    name: 'Git & GitHub',
    category: 'Tools & Platforms',
    level: 92,
    iconName: 'Git',
    description: 'Version control, collaborative branches, code merges, and source structures.',
  },
  {
    name: 'WordPress',
    category: 'Tools & Platforms',
    level: 85,
    iconName: 'WordPress',
    description: 'Theme customization, plugin integrations, and site performance tuning.',
  },
  {
    name: 'Postman',
    category: 'Tools & Platforms',
    level: 88,
    iconName: 'Postman',
    description: 'Endpoint simulation, environment parameters, and manual API validations.',
  },

  // Soft Skills
  {
    name: 'Agile & Scrum',
    category: 'Soft Skills',
    level: 90,
    iconName: 'Brain',
    description: 'Working in fast-paced sprints, daily standups, and cooperative alignments.',
  },
  {
    name: 'Team Leadership',
    category: 'Soft Skills',
    level: 85,
    iconName: 'Message',
    description: 'Guiding small engineering groups and reviewing code routines for safety.',
  },
  {
    name: 'Analytical Debugging',
    category: 'Soft Skills',
    level: 92,
    iconName: 'Clock',
    description: 'Isolating browser and database execution bottlenecks for speedy patches.',
  },
];

export const experienceData: Experience[] = [
  {
    id: 'exp-1',
    role: 'Full-Time Freelance Full-Stack Developer',
    company: 'DevBeans',
    location: 'Remote',
    period: 'Aug 2025 - Present',
    description: [
      'Engineered custom CRM systems and business dashboards for enterprise clients, automating workflow pipelines and reducing manual data-entry overhead.',
      'Developed secure backend modules and database schemas using PHP and MySQL, implementing robust REST APIs and granular access control list (ACL) rules.',
      'Implemented highly responsive frontend layouts and interactive UI components using React.js and TypeScript, improving overall user retention.',
      'Crafted custom WordPress websites and theme modules for business clients, handling custom plugin architecture and layout designs.'
    ],
    skillsAcquired: ['React.js', 'TypeScript', 'PHP', 'MySQL', 'REST APIs', 'Dashboard Design', 'WordPress', 'UI Component Development'],
  },
  {
    id: 'exp-2',
    role: 'Technical Lead – Full-Stack Developer',
    company: 'Codeshell Technologies',
    location: 'Chennai, India',
    period: 'Oct 2024 - Jul 2025',
    description: [
      'Directed an engineering team in building secure CRM and inventory management platforms, delivering all core milestones ahead of schedule.',
      'Refactored legacy PHP and Laravel codebases and optimized complex SQL database queries, improving application load performance and backend processing efficiency.',
      'Instituted Agile methodologies and conducted weekly team code reviews to ensure compliance with best practices and minimize post-deployment bugs.',
      'Delivered both collaborative team-based software products and independent full-stack web applications from initial requirements to final deployment.'
    ],
    skillsAcquired: ['Team Leadership', 'Laravel', 'PHP', 'React', 'MySQL', 'Tailwind CSS', 'Bootstrap CSS', 'HTML', 'JS', 'Agile/Scrum', 'Code Reviews', 'Independent Projects', 'Team Projects'],
  },
  {
    id: 'exp-3',
    role: 'Frontend and UI/UX Developer',
    company: 'Codeshell Technologies',
    location: 'Remote, Chennai',
    period: 'Nov 2023 - Sep 2024',
    description: [
      'Created reusable React.js UI components and modular design elements, streamlining frontend development workflow across the engineering team.',
      'Converted high-fidelity, complex Figma wireframes into pixel-perfect, responsive user interfaces using HTML5 and CSS3.',
      'Integrated frontend applications with REST APIs, handling dynamic data rendering for high-traffic public-facing platforms.'
    ],
    skillsAcquired: ['React.js', 'UI/UX Design', 'Figma to Code', 'REST API Integration', 'HTML5/CSS3'],
  },
  {
    id: 'exp-4',
    role: 'Teaching Professional',
    company: 'Education Sector',
    location: 'Karaikudi, Tamil Nadu',
    period: 'Nov 2023 - Sep 2024',
    description: [
      'Instructed students on computer science fundamentals and modern programming paradigms, achieving strong course completion and understanding.',
      'Guided students through targeted debugging exercises and code logic building, improving average practical test performance.',
      'Taught foundational and practical concepts in HTML, CSS, PHP, MySQL, and C++.'
    ],
    skillsAcquired: ['Computer Science Fundamentals', 'Programming Instruction', 'Debugging Assistance', 'HTML', 'CSS', 'PHP', 'MySQL', 'C++'],
  },
  {
    id: 'exp-5',
    role: 'Frontend Developer Intern',
    company: 'Senchola Technology Solutions',
    location: 'Remote',
    period: 'Oct 2023 - Dec 2023',
    description: [
      'Constructed responsive frontend layouts using React.js and Bootstrap, ensuring perfect cross-device compatibility and browser layouts.',
      'Assisted lead developers in debugging complex UI components and optimizing web page rendering speeds and scripts.'
    ],
    skillsAcquired: ['HTML', 'CSS', 'JavaScript', 'React.js', 'Bootstrap', 'Cross-Device Compatibility', 'Component Debugging'],
  },
];

export const projectsData: Project[] = [
  {
    id: 'proj-1',
    title: 'Mortoplux CRM Platform',
    subtitle: 'Centralized CRM & Access Control',
    description: 'A centralized client dashboard to manage secure directories and client records with Role-Based Access Control (RBAC).',
    longDescription: 'Developed a robust client relationship management platform equipped to manage enterprise records securely. Features strict Role-Based Access Control (RBAC) to segment manager and operator directories, and integrates multi-metric reporting and business analytics tools to support data-driven decisions and increase sales efficiency.',
    technologies: ['React.js', 'PHP', 'MySQL', 'REST API', 'RBAC Security'],
    category: 'Admin / CRM',
    githubUrl: 'https://github.com/rkvkeerthana/almino-crm',
    liveUrl: 'https://keerthanavalli-portfolio-fsd.vercel.app/',
    stats: [
      { label: 'Record Volume', value: 'Enterprise Scale' },
      { label: 'Access Control', value: 'Strict RBAC' },
      { label: 'Sales Efficiency', value: 'Highly Optimized' },
    ],
    keyFeatures: [
      'Client relationship directories with dynamic search and instant filtering systems.',
      'Role-Based Access Control (RBAC) preventing unauthorized endpoint access.',
      'Comprehensive reporting tools rendering real-time business and operations insights.',
      'Polished and responsive user dashboards with smooth tabular controls.',
    ],
  },
  {
    id: 'proj-2',
    title: 'ServiceApp',
    subtitle: 'Technician Work Management Platform',
    description: 'An operational task assignment and attendance tracking system for field service personnel.',
    longDescription: 'Architected and developed an internal technician workflow utility for dispatch and dispatch tracking. Streamlined manual service assignment, automated live attendance checks, and provided direct administrative dashboards offering comprehensive visibility into workforce task status.',
    technologies: ['PHP', 'MySQL', 'JavaScript', 'HTML5/CSS3'],
    category: 'Admin / CRM',
    githubUrl: 'https://github.com/rkvkeerthana/ServiceApp',
    liveUrl: 'https://keerthanavalli-portfolio-fsd.vercel.app/',
    stats: [
      { label: 'Service Personnel', value: 'Field Team' },
      { label: 'Workflow Visibility', value: 'Comprehensive' },
      { label: 'Dispatch Control', value: 'Automated' },
    ],
    keyFeatures: [
      'Live task scheduling and instant geographical assignment tracking.',
      'Technician attendance verification logbooks with database security backups.',
      'Role-based dashboard permissions for branch managers and administrative leads.',
      'Dynamic state indicators showcasing progress phases from queue to completion.',
    ],
  },
  {
    id: 'proj-3',
    title: 'HallBooky & ShineStays Booking Platform',
    subtitle: 'Hotel and Event Booking Engine',
    description: 'An end-to-end hotel and event reservation booking engine with real-time validation.',
    longDescription: 'Designed and engineered an automated booking ecosystem preventing double bookings through real-time reservation scheduling validation. Optimizes user acquisition with highly responsive visual templates, leading to an increase in mobile conversions and reservation confirmations.',
    technologies: ['React.js', 'Tailwind CSS', 'PHP', 'MySQL'],
    category: 'Full-Stack',
    githubUrl: 'https://github.com/rkvkeerthana/HallBooky-ShineStays',
    liveUrl: 'https://keerthanavalli-portfolio-fsd.vercel.app/',
    stats: [
      { label: 'Mobile Conversions', value: 'Significantly Increased' },
      { label: 'Double Bookings', value: 'Zero Collisions' },
      { label: 'Scheduling Validation', value: 'Real-time' },
    ],
    keyFeatures: [
      'Automated double-booking prevention engine verifying dates and spaces instantaneously.',
      'Fully responsive reservation cart styled with fluid Tailwind CSS layouts.',
      'Interactive availability calendar showing real-time slot statuses.',
      'Administrative controls to adjust active room prices and seasonal availability.',
    ],
  },
  {
    id: 'proj-4',
    title: 'Coupon Management System',
    subtitle: 'Automated Merchant Coupon Workflows',
    description: 'A UI/UX Figma and AWS-based, mobile-friendly app & website featuring an Admin CRM and user mobile website.',
    longDescription: 'Engineered a comprehensive, high-fidelity UI/UX Figma-designed and AWS-hosted, mobile-friendly application and website system. It integrates an interactive Admin CRM merchant portal for automating workflow distribution with a highly responsive AWS-powered mobile website for seamless end-user coupon redemptions.',
    technologies: ['React.js', 'PHP', 'MySQL', 'REST API', 'Figma', 'AWS'],
    category: 'Admin / CRM',
    githubUrl: 'https://github.com/rkvkeerthana/Coupon-Management-System',
    liveUrl: 'https://keerthanavalli-portfolio-fsd.vercel.app/',
    stats: [
      { label: 'Mobile Design', value: 'Highly Optimized' },
      { label: 'Cloud Host', value: 'AWS Infrastructure' },
      { label: 'Daily Redemptions', value: 'Seamless Processing' },
    ],
    keyFeatures: [
      'Figma design system mapping with high-fidelity mobile-friendly wireframes and UI workflows.',
      'Robust AWS cloud infrastructure hosting both the Admin CRM portal and the user mobile website.',
      'Automated merchant distribution CRM managing and processing daily coupon redemptions.',
      'Advanced analytics showing live redemption status with secure, zero-collision check-in codes.',
    ],
  },
  {
    id: 'proj-5',
    title: 'ZarStore',
    subtitle: 'Online Store E-Commerce Application',
    description: 'An e-commerce store featuring dynamic catalog search, cart logics, and Laravel checkouts.',
    longDescription: 'Engineered an online store with rich product catalogs, complex cart utilities, and secure Laravel checkout routes. Supports listing management, authentication, order tracking, and payment processing for daily transactions.',
    technologies: ['Laravel framework', 'Tailwind CSS', 'MySQL'],
    category: 'Full-Stack',
    githubUrl: 'https://github.com/rkvkeerthana/ZarStore',
    liveUrl: 'https://keerthanavalli-portfolio-fsd.vercel.app/',
    stats: [
      { label: 'Listed Products', value: 'Extensive Catalog' },
      { label: 'Daily Transactions', value: 'High Capacity' },
      { label: 'Tailwind Design', value: 'Mobile-first' },
    ],
    keyFeatures: [
      'Laravel-powered MVC authentication and secure session states.',
      'Flexible shopping carts and price sum calculators using client states.',
      'Order dispatch status dashboard tracking items from warehouse to delivery.',
      'Fully fluid, mobile-first layouts using Tailwind CSS grid modules.',
    ],
  },
  {
    id: 'proj-6',
    title: 'Dealer Inventory Management System',
    subtitle: 'Automated Stocks & Invoices',
    description: 'An inventory tracking and supplier system reducing discrepancies and invoice generation time.',
    longDescription: 'Designed dynamic tracking modules ensuring accurate inventory records, lowering stock discrepancies significantly. Integrates automated invoice creation, speeding up billing cycles and supplier transactions.',
    technologies: ['PHP', 'MySQL', 'JavaScript', 'HTML5/CSS3'],
    category: 'Admin / CRM',
    githubUrl: 'https://github.com/rkvkeerthana/Dealer-Inventory-Management-System',
    liveUrl: 'https://keerthanavalli-portfolio-fsd.vercel.app/',
    stats: [
      { label: 'Discrepancy Reduction', value: 'Substantial' },
      { label: 'Invoice Generation', value: 'Highly Accelerated' },
      { label: 'Supplier Databases', value: 'Automated' },
    ],
    keyFeatures: [
      'Automatic warning alerts for low-volume inventory levels.',
      'Supplier details ledger with relational item mapping.',
      'PDF-parsable billing invoice generation modules.',
      'Fast full-text database inventory searches.',
    ],
  },
  {
    id: 'proj-7',
    title: 'Studios Web Application',
    subtitle: 'Optimized Business Web Solution',
    description: 'A customized WordPress business portal with optimized speed and responsive templates.',
    longDescription: 'Re-designed customized themes and custom PHP plugins for business portals, boosting site loading speed and lowering user bounce rates through elegant layouts.',
    technologies: ['WordPress', 'PHP', 'CSS3', 'SEO Best Practices'],
    category: 'Frontend',
    githubUrl: 'https://github.com/rkvkeerthana/Studios-Web-Application',
    liveUrl: 'https://keerthanavalli-portfolio-fsd.vercel.app/',
    stats: [
      { label: 'Site Speed Increase', value: 'Substantial Boost' },
      { label: 'Bounce Rate Decrease', value: 'Reduced' },
      { label: 'Layout Design', value: 'Pixel-perfect' },
    ],
    keyFeatures: [
      'High-performance custom PHP WordPress plugins.',
      'Fully responsive client portfolios compatible with all mobile screens.',
      'Clean SEO-optimized HTML tags.',
      'Efficient visual structure displaying corporate services and contact info.',
    ],
  },
  {
    id: 'proj-8',
    title: 'SaaS Analytics Dashboard UI',
    subtitle: 'Figma High-Fidelity Design System',
    description: 'An enterprise SaaS analytics dashboard designed in Figma with comprehensive design systems, dark/light themes, and interactive prototyping.',
    longDescription: 'Created a comprehensive, high-fidelity design system and interactive prototypes for an enterprise-level SaaS analytics dashboard. Modeled using Figma auto-layouts, custom responsive grids, and flexible design tokens. The system features modular UI components (buttons, input fields, tables, charts) supporting both dark and light modes with perfect semantic color mappings and responsive variants.',
    technologies: ['Figma', 'Prototyping', 'Design Systems', 'UX Research', 'UI Components'],
    category: 'UI/UX (Figma)',
    liveUrl: 'https://keerthanavalli-portfolio-fsd.vercel.app/',
    stats: [
      { label: 'UI Component Library', value: 'Comprehensive' },
      { label: 'Page Templates', value: 'Responsive Layouts' },
      { label: 'User Journeys', value: 'Mapped Pathways' },
    ],
    keyFeatures: [
      'Comprehensive design token mapping for seamless light/dark mode styling handoffs.',
      'Dynamic Figma auto-layout and variant properties ensuring bulletproof responsiveness.',
      'Interactive high-fidelity page prototypes demonstrating interactive state behaviors (hover, active, disabled).',
      'User persona mapping and card sorting diagrams supporting the dashboard\'s layout architecture.',
    ],
  },
  {
    id: 'proj-9',
    title: 'E-Commerce Mobile App Experience',
    subtitle: 'Wireframes & Interactive Prototypes',
    description: 'Mobile e-commerce experience designed with high usability checkout screens, search filters, and swipe micro-animations.',
    longDescription: 'Led UX research and user-flow journey planning to design an iOS/Android e-commerce mobile application. Focused on optimizing checkout funnel conversions, implementing clean multi-layered search filters, and crafting playful micro-animations to support intuitive user exploration. Delivered high-fidelity, client-testable prototypes directly in Figma.',
    technologies: ['Figma', 'Wireframing', 'User Flows', 'Interactive Prototyping', 'Mobile UX'],
    category: 'UI/UX (Figma)',
    liveUrl: 'https://keerthanavalli-portfolio-fsd.vercel.app/',
    stats: [
      { label: 'Checkout Flow', value: 'Streamlined' },
      { label: 'Usability Rating', value: 'Excellent' },
      { label: 'Screen Layouts', value: 'Comprehensive' },
    ],
    keyFeatures: [
      'Engineered an intuitive single-screen checkout flow reducing transaction friction.',
      'Stunning high-fidelity interactive animations showcasing sliding drawers, search overlays, and card flips.',
      'Low-fidelity wireframe blueprints showing initial user flow and page-level information layouts.',
      'Detailed component guidelines specifying margin, typography scales, and tap target safe-zones (44px+).',
    ],
  },
  {
    id: 'proj-10',
    title: 'Modern Interactive Portfolio',
    subtitle: 'Responsive Developer Space',
    description: 'Interactive developer portfolio with custom styles, responsive prints, and smooth section timelines.',
    longDescription: 'Crafted a beautiful developer portfolio with a custom theme, visual depth effects, print-ready document engines, and fully modular responsive panels. Built utilizing React.js, Tailwind CSS, and Motion React.',
    technologies: ['React.js', 'Tailwind CSS', 'Motion React', 'TypeScript'],
    category: 'Frontend',
    githubUrl: 'https://github.com/rkvkeerthana/keerthanavalli-portfolio-fsd',
    liveUrl: 'https://keerthanavalli-portfolio-fsd-model-gg4asf80r.vercel.app/',
    stats: [
      { label: 'Print Success', value: 'Optimized PDF' },
      { label: 'Core Modules', value: 'Modular Panels' },
      { label: 'Asset Size', value: 'Highly Optimized' },
    ],
    keyFeatures: [
      'Print-ready ATS document layout stylesheet with automated page break calculations.',
      'Sophisticated scroll-triggered animations and tab-switching micro-interactions.',
      'Highly configurable and extensible content-driven data mapping schema.',
    ],
  },
  {
    id: 'proj-11',
    title: 'LARA SHOPY',
    subtitle: 'Laravel E-Commerce Platform',
    description: 'A fully functional online storefront featuring product catalogs, responsive cart management, and secure order workflows.',
    longDescription: 'Engineered a comprehensive e-commerce platform utilising the PHP Laravel MVC framework. Designed and integrated secure customer authentication, a dynamic product catalog with search capabilities and category filtering, a modular shopping cart state manager, and structured checkout routes backed by relational MySQL schemas.',
    technologies: ['Laravel', 'PHP', 'MySQL', 'Tailwind CSS', 'Blade Templates'],
    category: 'Full-Stack',
    githubUrl: 'https://github.com/rkvkeerthana/Lara-Shopy',
    liveUrl: 'https://lara-shopy.vercel.app/',
    stats: [
      { label: 'Backend Architecture', value: 'Laravel MVC' },
      { label: 'Database Relations', value: 'MySQL Schemas' },
      { label: 'Responsive Design', value: 'Tailwind CSS' },
    ],
    keyFeatures: [
      'Secure user authentication and registration states managed by Laravel security guards.',
      'Responsive and intuitive product category browser with quick search capabilities.',
      'Client-synchronized shopping cart managing dynamic additions, removals, and total tallies.',
      'Robust database integrity supporting structured checkout and order histories.',
    ],
  },
  {
    id: 'proj-12',
    title: 'ZETA EXPEDITIONS',
    subtitle: 'Tours & Travels Platform',
    description: 'An immersive travel and tour expedition platform featuring destination catalogs, responsive filters, and elegant motion transitions.',
    longDescription: 'Designed and developed a highly interactive travel booking and expedition web application using React and Vite. Integrated fluid layout animations using Motion React to enhance user journey maps, styled responsive content spaces with Tailwind CSS, and optimized search and filter queries for quick destination exploration. Constructed fully with TypeScript to ensure standard, robust type safety.',
    technologies: ['React.js', 'Vite', 'TypeScript', 'Tailwind CSS', 'Motion React', 'Lucide Icons'],
    category: 'Frontend',
    githubUrl: 'https://github.com/rkvkeerthana/ZETA-EXPEDITIONS',
    liveUrl: 'https://zeta-expeditions.vercel.app/',
    stats: [
      { label: 'Development Tooling', value: 'Vite & TypeScript' },
      { label: 'Interactive Motion', value: 'Motion React' },
      { label: 'Styling Framework', value: 'Tailwind CSS' },
    ],
    keyFeatures: [
      'Interactive destination browsing and tours interface with real-time dynamic filters.',
      'Fluid page and layout transition effects powered by Motion React.',
      'Fully responsive visual design optimized across all desktop, tablet, and mobile displays.',
      'Type-safe components and clean modular code architecture with strict TypeScript rules.',
    ],
  },
  {
    id: 'proj-13',
    title: 'Almino CRM',
    subtitle: 'Construction Multi-Domain Design System',
    description: 'High-fidelity Figma UI/UX project for a multi-branch, multi-domain large-scale construction CRM with secure authentication & authorization panels.',
    longDescription: 'Created a highly detailed, comprehensive multi-branch and multi-domain CRM system design system in Figma specifically tailored for large-scale construction enterprises. The design delivers fully functional role-based authentication and authorization flows, robust operator/foreman/manager CRM panels, site allocation workflows, and domain separation interfaces to manage distinct branches and sectors seamlessly.',
    technologies: ['Figma', 'Prototyping', 'Design Systems', 'Role-Based Flow', 'Construction UX'],
    category: 'UI/UX (Figma)',
    liveUrl: 'https://www.figma.com/design/aNveZepzAl2vIUARkxwdV4/Almino?node-id=0-1&t=PpaSE9meVtYRloDe-1',
    stats: [
      { label: 'Branch Channels', value: 'Multi-Branch' },
      { label: 'Authorization', value: 'Specific Auth & Auth' },
      { label: 'Target Sector', value: 'Construction' },
    ],
    keyFeatures: [
      'Complete high-fidelity Figma workspace displaying multi-domain dashboard navigation.',
      'Custom authentication & authorization panels mapping specialized user permissions (Admin, Branch Manager, Onsite Foreman).',
      'Advanced components for resource allocation, machinery scheduling, and branch inventory tracking.',
      'Interactive state flows showcasing dynamic login security verification.',
    ],
  },
  {
    id: 'proj-14',
    title: 'Travel Booky',
    subtitle: 'Tours & Travels Booking Platform',
    description: 'A modern, mobile-friendly tours & travels booking platform featuring a beautiful 2-theme model website styled with React, Vite, and TypeScript.',
    longDescription: 'Created Travel Booky, an elegant and fully responsive booking website for tours and travels. Built with React, Vite, and TypeScript for robust type safety and fluid performance. Implemented a custom 2-theme design model supporting seamless transitions between gorgeous light and dark theme modes. Features modular layouts, responsive user interfaces, and custom vacation search filter tools.',
    technologies: ['React.js', 'Vite', 'TypeScript', 'Tailwind CSS', '2-Theme Model'],
    category: 'Frontend',
    liveUrl: 'https://travel-booky.vercel.app/',
    stats: [
      { label: 'Theme Architecture', value: '2-Theme Model' },
      { label: 'Development Tooling', value: 'Vite & TypeScript' },
      { label: 'Target Sector', value: 'Tours & Travels' },
    ],
    keyFeatures: [
      'Custom dual-theme mode (light and dark) supporting persistent preferences.',
      'Comprehensive search and filter controls for vacation package and tour catalogs.',
      'Fully responsive UI layout optimized across desktop, tablet, and mobile browsers.',
      'Robust type-safe components with clean modular React state architecture.',
    ],
  },
  {
    id: 'proj-15',
    title: 'Wedding Invite',
    subtitle: 'Animated Digital RSVP & Invitation Platform',
    description: 'An elegant, animated digital wedding invitation card featuring interactive RSVP workflows and dynamic Google Calendar reminders.',
    longDescription: 'Developed a personalized, beautifully animated digital wedding invitation experience. Built with React, Vite, and TypeScript to deliver fluid performance and premium aesthetics. Integrates a real-time RSVP submission system powered by Google Apps Script, mapping guest responses directly into a secure spreadsheet, along with integrated Google Calendar invitation syncing to help guests easily schedule reminders.',
    technologies: ['React.js', 'Vite', 'TypeScript', 'Google Apps Script', 'Tailwind CSS', 'Google Calendar Sync'],
    category: 'Frontend',
    liveUrl: 'https://wedding-invite-pink-tau.vercel.app/',
    stats: [
      { label: 'Theme Aesthetics', value: 'Animated & Elegant' },
      { label: 'RSVP Processing', value: 'Google Apps Script' },
      { label: 'Integrations', value: 'Google Calendar Sync' },
    ],
    keyFeatures: [
      'Bespoke animated transitions and visual greeting cards celebrating the couple.',
      'Interactive RSVP flow writing submissions securely to Google Sheets via secure Apps Script API.',
      'Direct Google Calendar sync enabling guests to add key events to their schedules with one click.',
      'Highly optimized, mobile-first design crafted for seamless display on smartphone screens.',
    ],
  },
];

export const educationData: Education[] = [
  {
    id: 'edu-1',
    degree: 'M.E. Communication Systems',
    institution: 'Agni College of Technology',
    institutionUrl: 'https://www.act.edu.in/',
    location: 'Chennai, Tamil Nadu, India',
    period: 'Post-Graduate',
    grade: 'First Class with Distinction',
    specialization: 'Communication Networks, System Architecture, Signal Integrity',
    highlights: [
      'Studied advanced communication protocols, enterprise systems, and networking architectures.',
      'Acquired strong analytical problem-solving skills and structured research methodologies.',
    ],
  },
  {
    id: 'edu-2',
    degree: 'B.E. Electronics and Communication Engineering',
    institution: 'Agni College of Technology',
    institutionUrl: 'https://www.act.edu.in/',
    location: 'Chennai, Tamil Nadu, India',
    period: 'Graduate',
    grade: 'First Class',
    specialization: 'Digital Circuits, Microprocessors, Software Engineering, Database Systems',
    highlights: [
      'Consistently achieved strong academic standing across software and core engineering subjects.',
      'Developed foundational software architectures and embedded programming solutions.',
    ],
  },
];
